site_name: نظيم موقف العاملين
theme:
  name: 'material'
  features:
    - 'navigation.tabs'
    - 'navigation.sections'
    - 'toc.integrate'
    - 'navigation.top'
    - 'search.suggest'
    - 'search.highlight'
    - 'content.tabs.link'
    - 'content.code.annotation'
    - 'content.code.copy'
  language: 'ar'
  palette:
    - scheme: 'default'
      toggle:
        icon: 'material/toggle-switch-off-outline'
        name: 'Switch to dark mode'
      primary: 'teal'
      accent: 'purple' 
    - scheme: 'slate' 
      toggle:
        icon: 'material/toggle-switch'
        name: 'Switch to light mode'    
      primary: 'teal'
      accent: 'lime'

# plugins:
#   - social
#   - search

extra:
  # social:
  #   - icon: 'fontawesome/brands/github-alt'
  #     link: 'https://github.com/james-willett'
  #   - icon: 'fontawesome/brands/twitter'
  #     link: 'https://twitter.com/TheJamesWillett'
  #   - icon: 'fontawesome/brands/linkedin'
  #     link: 'https://www.linkedin.com/in/willettjames/'
  copy_files:
  - 'images/*.png'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: 'true'
  - 'pymdownx.inlinehilite'
  - 'pymdownx.snippets'
  - 'admonition'
  - pymdownx.arithmatex:
      generic: 'true'
  - 'footnotes'
  - 'pymdownx.details'
  - 'pymdownx.superfences'
  - 'pymdownx.mark'
  - 'attr_list'
  - pymdownx.emoji:
      # emoji_index: '!!python/name:materialx.emoji.twemoji'
      # emoji_generator: '!!python/name:materialx.emoji.to_svg'

# extra_css:
#   - 'stylesheets/extra.css'
# extra_javascript:
#   - 'javascripts/extra.js'


copyright: |
  <a href="#"  target="_blank" rel="noopener">EmpSituation System Manual</a> &copy; 2023

